#define SECRET_OPTIONAL_DNS ""
#define SECRET_OPTIONAL_GATEWAY ""
#define SECRET_OPTIONAL_IP ""
#define SECRET_OPTIONAL_NETMASK ""

// SMTP credentials (fill with real values on device)
#define SECRET_SMTP_SERVER ""
#define SECRET_SMTP_PORT 2525
#define SECRET_SMTP_USERNAME ""
#define SECRET_SMTP_PASSWORD ""

// Fault email metadata
#define SECRET_FAULT_EMAIL_FROM_NAME ""
#define SECRET_FAULT_EMAIL_FROM_ADDR ""
#define SECRET_FAULT_EMAIL_RECIPIENT_1_NAME ""
#define SECRET_FAULT_EMAIL_RECIPIENT_1_ADDR ""
#define SECRET_FAULT_EMAIL_RECIPIENT_2_NAME ""
#define SECRET_FAULT_EMAIL_RECIPIENT_2_ADDR ""
