#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include <Arduino_NetworkConfigurator.h>
#include <configuratorAgents/agents/BLEAgent.h>
#include <configuratorAgents/agents/SerialAgent.h>
void onVfd1AccelTimeSecChange();
void onVfd1SpeedSetHzChange();
void onVfd2AccelTimeSecChange();
void onVfd2SpeedSetHzChange();
void onPulseSecondsChange();
void onVfd2AlarmCodeChange();
void onTower0BypassChange();
void onTower0IrrEnableChange();
void onTower1BypassChange();
void onTower1IrrEnableChange();
void onTower2BypassChange();
void onTower2IrrEnableChange();
void onTower3BypassChange();
void onTower3IrrEnableChange();
void onTower4BypassChange();
void onTower4IrrEnableChange();
void onTower5BypassChange();
void onTower5IrrEnableChange();
void onTower6BypassChange();
void onTower6IrrEnableChange();
void onTower7BypassChange();
void onTower7IrrEnableChange();
void onVfd1RunCmdChange();
void onVfd2RunCmdChange();

String ipAddressStr;
String lastOutageType;
String uptimeStr;
float vfd1AccelTimeSec;
float vfd1CurrentLimitPct;
float vfd1DecelTimeSec;
float vfd1MotorCurrentPct;
float vfd1PeakCurrentPct;
float vfd1SpeedFbHz;
float vfd1SpeedSetHz;
float vfd2AccelTimeSec;
float vfd2CurrentLimitPct;
float vfd2DecelTimeSec;
float vfd2MotorCurrentPct;
float vfd2PeakCurrentPct;
float vfd2SpeedFbHz;
float vfd2SpeedSetHz;
int deltaMin0;
int deltaMin1;
int deltaMin2;
int deltaMin3;
int deltaMin4;
int deltaMin5;
int deltaMin6;
int deltaMin7;
int lastOfflineDurationSec;
int lastReconnectUptimeSec;
int lastTrigAgoMin0;
int lastTrigAgoMin1;
int lastTrigAgoMin2;
int lastTrigAgoMin3;
int lastTrigAgoMin4;
int lastTrigAgoMin5;
int lastTrigAgoMin6;
int lastTrigAgoMin7;
int networkLossCount;
int powerLossCount;
int pulseSeconds;
int tower0LastEdgeMin;
int tower0LastIntervalMin;
int tower0TrayCount;
int tower1LastEdgeMin;
int tower1LastIntervalMin;
int tower1TrayCount;
int tower2LastEdgeMin;
int tower2LastIntervalMin;
int tower2TrayCount;
int tower3LastEdgeMin;
int tower3LastIntervalMin;
int tower3TrayCount;
int tower4LastEdgeMin;
int tower4LastIntervalMin;
int tower4TrayCount;
int tower5LastEdgeMin;
int tower5LastIntervalMin;
int tower5TrayCount;
int tower6LastEdgeMin;
int tower6LastIntervalMin;
int tower6TrayCount;
int tower7LastEdgeMin;
int tower7LastIntervalMin;
int tower7TrayCount;
int trigCount0;
int trigCount1;
int trigCount2;
int trigCount3;
int trigCount4;
int trigCount5;
int trigCount6;
int trigCount7;
int uptimeSec;
int vfd1AlarmCode;
int vfd1StatusWord;
int vfd2AlarmCode;
int vfd2StatusWord;
bool inState0;
bool inState1;
bool inState2;
bool inState3;
bool inState4;
bool inState5;
bool inState6;
bool inState7;
bool outState0;
bool outState1;
bool outState2;
bool outState3;
bool outState4;
bool outState5;
bool outState6;
bool outState7;
bool tower0Bypass;
bool tower0Fault;
bool tower0IrrEnable;
bool tower0Running;
bool tower1Bypass;
bool tower1Fault;
bool tower1IrrEnable;
bool tower1Running;
bool tower2Bypass;
bool tower2Fault;
bool tower2IrrEnable;
bool tower2Running;
bool tower3Bypass;
bool tower3Fault;
bool tower3IrrEnable;
bool tower3Running;
bool tower4Bypass;
bool tower4Fault;
bool tower4IrrEnable;
bool tower4Running;
bool tower5Bypass;
bool tower5Fault;
bool tower5IrrEnable;
bool tower5Running;
bool tower6Bypass;
bool tower6Fault;
bool tower6IrrEnable;
bool tower6Running;
bool tower7Bypass;
bool tower7Fault;
bool tower7IrrEnable;
bool tower7Running;
bool vfd1CommFault;
bool vfd1RunCmd;
bool vfd2CommFault;
bool vfd2RunCmd;

KVStore kvStore;
BLEAgentClass BLEAgent;
SerialAgentClass SerialAgent;
EthernetConnectionHandler ArduinoIoTPreferredConnection;
NetworkConfiguratorClass NetworkConfigurator(ArduinoIoTPreferredConnection);

void initProperties(){
  NetworkConfigurator.addAgent(BLEAgent);
  NetworkConfigurator.addAgent(SerialAgent);
  NetworkConfigurator.setStorage(kvStore);
  // For changing the default reset pin uncomment and set your preferred pin. Use DISABLE_PIN for disabling the reset procedure.
  //NetworkConfigurator.setReconfigurePin(your_pin);
  ArduinoCloud.setConfigurator(NetworkConfigurator);

  ArduinoCloud.addProperty(ipAddressStr, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lastOutageType, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(uptimeStr, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vfd1AccelTimeSec, READWRITE, ON_CHANGE, onVfd1AccelTimeSecChange);
  ArduinoCloud.addProperty(vfd1CurrentLimitPct, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vfd1DecelTimeSec, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vfd1MotorCurrentPct, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vfd1PeakCurrentPct, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vfd1SpeedFbHz, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vfd1SpeedSetHz, READWRITE, ON_CHANGE, onVfd1SpeedSetHzChange);
  ArduinoCloud.addProperty(vfd2AccelTimeSec, READWRITE, ON_CHANGE, onVfd2AccelTimeSecChange);
  ArduinoCloud.addProperty(vfd2CurrentLimitPct, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vfd2DecelTimeSec, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vfd2MotorCurrentPct, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vfd2PeakCurrentPct, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vfd2SpeedFbHz, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vfd2SpeedSetHz, READWRITE, ON_CHANGE, onVfd2SpeedSetHzChange);
  ArduinoCloud.addProperty(deltaMin0, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(deltaMin1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(deltaMin2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(deltaMin3, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(deltaMin4, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(deltaMin5, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(deltaMin6, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(deltaMin7, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lastOfflineDurationSec, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lastReconnectUptimeSec, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lastTrigAgoMin0, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lastTrigAgoMin1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lastTrigAgoMin2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lastTrigAgoMin3, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lastTrigAgoMin4, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lastTrigAgoMin5, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lastTrigAgoMin6, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lastTrigAgoMin7, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(networkLossCount, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(powerLossCount, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pulseSeconds, READWRITE, ON_CHANGE, onPulseSecondsChange);
  ArduinoCloud.addProperty(tower0LastEdgeMin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower0LastIntervalMin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower0TrayCount, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower1LastEdgeMin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower1LastIntervalMin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower1TrayCount, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower2LastEdgeMin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower2LastIntervalMin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower2TrayCount, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower3LastEdgeMin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower3LastIntervalMin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower3TrayCount, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower4LastEdgeMin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower4LastIntervalMin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower4TrayCount, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower5LastEdgeMin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower5LastIntervalMin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower5TrayCount, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower6LastEdgeMin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower6LastIntervalMin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower6TrayCount, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower7LastEdgeMin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower7LastIntervalMin, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower7TrayCount, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(trigCount0, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(trigCount1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(trigCount2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(trigCount3, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(trigCount4, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(trigCount5, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(trigCount6, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(trigCount7, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(uptimeSec, READ, ON_CHANGE, NULL, 60);
  ArduinoCloud.addProperty(vfd1AlarmCode, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vfd1StatusWord, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vfd2AlarmCode, READWRITE, ON_CHANGE, onVfd2AlarmCodeChange);
  ArduinoCloud.addProperty(vfd2StatusWord, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(inState0, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(inState1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(inState2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(inState3, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(inState4, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(inState5, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(inState6, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(inState7, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(outState0, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(outState1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(outState2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(outState3, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(outState4, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(outState5, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(outState6, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(outState7, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower0Bypass, READWRITE, ON_CHANGE, onTower0BypassChange);
  ArduinoCloud.addProperty(tower0Fault, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower0IrrEnable, READWRITE, ON_CHANGE, onTower0IrrEnableChange);
  ArduinoCloud.addProperty(tower0Running, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower1Bypass, READWRITE, ON_CHANGE, onTower1BypassChange);
  ArduinoCloud.addProperty(tower1Fault, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower1IrrEnable, READWRITE, ON_CHANGE, onTower1IrrEnableChange);
  ArduinoCloud.addProperty(tower1Running, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower2Bypass, READWRITE, ON_CHANGE, onTower2BypassChange);
  ArduinoCloud.addProperty(tower2Fault, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower2IrrEnable, READWRITE, ON_CHANGE, onTower2IrrEnableChange);
  ArduinoCloud.addProperty(tower2Running, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower3Bypass, READWRITE, ON_CHANGE, onTower3BypassChange);
  ArduinoCloud.addProperty(tower3Fault, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower3IrrEnable, READWRITE, ON_CHANGE, onTower3IrrEnableChange);
  ArduinoCloud.addProperty(tower3Running, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower4Bypass, READWRITE, ON_CHANGE, onTower4BypassChange);
  ArduinoCloud.addProperty(tower4Fault, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower4IrrEnable, READWRITE, ON_CHANGE, onTower4IrrEnableChange);
  ArduinoCloud.addProperty(tower4Running, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower5Bypass, READWRITE, ON_CHANGE, onTower5BypassChange);
  ArduinoCloud.addProperty(tower5Fault, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower5IrrEnable, READWRITE, ON_CHANGE, onTower5IrrEnableChange);
  ArduinoCloud.addProperty(tower5Running, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower6Bypass, READWRITE, ON_CHANGE, onTower6BypassChange);
  ArduinoCloud.addProperty(tower6Fault, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower6IrrEnable, READWRITE, ON_CHANGE, onTower6IrrEnableChange);
  ArduinoCloud.addProperty(tower6Running, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower7Bypass, READWRITE, ON_CHANGE, onTower7BypassChange);
  ArduinoCloud.addProperty(tower7Fault, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tower7IrrEnable, READWRITE, ON_CHANGE, onTower7IrrEnableChange);
  ArduinoCloud.addProperty(tower7Running, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vfd1CommFault, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vfd1RunCmd, READWRITE, ON_CHANGE, onVfd1RunCmdChange);
  ArduinoCloud.addProperty(vfd2CommFault, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vfd2RunCmd, READWRITE, ON_CHANGE, onVfd2RunCmdChange);

}
